<br>
<br>

### 한 폴더안에 모든 json파일이 있을 경우

In [10]:
import os
import json
import pandas as pd
from collections import defaultdict

# 폴더 경로 설정
folder_path = './가공완료_몇개만/article_1121/json_0/'

# 결과를 저장할 딕셔너리 초기화
pub_subj_count = defaultdict(int)
pub_date_count = defaultdict(int)
entities_count = defaultdict(int)
word_count_distribution = defaultdict(int)
entity_classes_count = defaultdict(int)
total_entities = 0
total_word_count = 0

# 폴더 내의 모든 JSON 파일 처리
total_files = 0
for filename in os.listdir(folder_path):
    if filename.endswith('.json'):
        total_files += 1
        with open(os.path.join(folder_path, filename), 'r', encoding='utf-8-sig') as file:
            data = json.load(file)
            pub_subj = data['Pub_Subj']
            pub_date = data['Pub_date']
            sentences = data['data']

            # 결과에 값을 추가
            pub_subj_count[pub_subj] += 1
            # pub_date_count[pub_date] += 1
            pub_date_count[pub_date.split('-')[0]] += 1

            for sentence in sentences:
                entities = sentence['Entities']
                word_count = int(sentence['Word_Count'])
                word_count_distribution[word_count] += 1
                total_word_count += 1
                
                for entity in entities:
                    entity_value = entity['entity']
                    entity_class = entity['entityClass']
                    entities_count[entity_value] += 1
                    entity_classes_count[entity_class] += 1
                    total_entities += 1
                    

# 비율 계산 함수
def calculate_percentage(count_dict, total):
    return {key: f'{value / total * 100:.2f}%' for key, value in count_dict.items()}

# 비율 계산
pub_subj_percentages = calculate_percentage(pub_subj_count, total_files)
pub_date_percentages = calculate_percentage(pub_date_count, total_files)
entities_percentages = calculate_percentage(entities_count, total_entities)
word_count_percentages = calculate_percentage(word_count_distribution, total_word_count)
entity_classes_percentages = calculate_percentage(entity_classes_count, total_entities)

# 데이터프레임 생성
pub_subj_df = pd.DataFrame({'Pub_Subj 비율': pub_subj_percentages, 'Pub_Subj 개수': pub_subj_count})
pub_date_df = pd.DataFrame({'Pub_Date 비율': pub_date_percentages, 'Pub_Date 개수': pub_date_count})
entities_df = pd.DataFrame({'Entity 비율': entities_percentages, 'Entity 개수': entities_count})
word_count_df = pd.DataFrame({'Word_Count 비율': word_count_percentages, 'Word_Count 개수': word_count_distribution})
entity_classes_df = pd.DataFrame({'Entity 클래스 비율': entity_classes_percentages, 'Entity 클래스 개수': entity_classes_count})

# 결과 출력
print('Pub_Subj 데이터프레임:')
print(pub_subj_df)
print(sum(pub_subj_df['Pub_Subj 비율'].str.rstrip('%').astype(float)))

print('\nPub_Date 데이터프레임:')
print(pub_date_df)
print(sum(pub_date_df['Pub_Date 비율'].str.rstrip('%').astype(float)))

print('\nEntities 데이터프레임:')
print(entities_df)
print(sum(entities_df['Entity 비율'].str.rstrip('%').astype(float)))

print('\nWord_Count 데이터프레임:')
print(word_count_df)
print(sum(word_count_df['Word_Count 비율'].str.rstrip('%').astype(float)))

print('\nEntity 클래스 데이터프레임:')
print(entity_classes_df)
print(sum(entity_classes_df['Entity 클래스 비율'].str.rstrip('%').astype(float)))

Pub_Subj 데이터프레임:
                    Pub_Subj 비율  Pub_Subj 개수
Pulau Samalona           10.26%          822
Batik                     1.62%          130
Kerajaan Kalinyamat      16.89%         1353
Kopi Joss                16.26%         1303
Siwalima Museum           4.62%          370
Ternate                   1.19%           95
Air Terjun Oehala         1.82%          146
Anggi Lakes               1.86%          149
Ikat                      1.12%           90
Kawa Daun                 8.76%          702
Kebudayaan Buni          10.17%          815
Mount Trikora             1.22%           98
Paniai Lakes              0.20%           16
Pantai Lovina             0.04%            3
Pertamina                 2.42%          194
Pura Lingsar              3.96%          317
Pura Sakenan              0.11%            9
Sabang                    1.01%           81
Solok                     2.33%          187
Sriwijaya                 1.50%          120
Anggun                    0.75%           60
Baju bodo                 4.01%          321
Bambang                   3.89%          312
Bima                      0.96%           77
Charles Tambu             1.19%           95
GARUDA                    1.06%           85
Jabodetabek               0.64%           51
Kerajaan Kahuripan        0.01%            1
Kesultanan Deli           0.14%           11
100.01

Pub_Date 데이터프레임:
     Pub_Date 비율  Pub_Date 개수
2020      11.38%          912
2023       8.00%          641
2019       5.57%          446
2018       5.87%          470
2017      22.56%         1808
2022      15.30%         1226
2015       5.62%          450
2014       5.17%          414
2013       1.91%          153
2021      11.56%          926
2016       7.08%          567
100.02000000000001

Entities 데이터프레임:
                      Entity 비율  Entity 개수
Ampat                     0.04%         42
Papua                     0.97%        966
,                         1.55%       1550
Barat ,                   0.08%         84
Raja                      0.01%          5
...                         ...        ...
aktivis                   0.00%          1
khawatir                  0.00%          1
Atlet ,                   0.00%          1
Selatan Nova              0.00%          1
kawasan Bukit Barisan     0.00%          1

[8935 rows x 2 columns]
92.47000000000385

Word_Count 데이터프레임:
    Word_Count 비율  Word_Count 개수
22          3.02%           7545
13          5.24%          13077
35          0.78%           1937
38          0.53%           1322
12          5.24%          13096
..            ...            ...
221         0.00%              1
177         0.00%              1
167         0.00%              1
185         0.00%              1
187         0.00%              2

[216 rows x 2 columns]
99.88000000000014

Entity 클래스 데이터프레임:
                       Entity 클래스 비율  Entity 클래스 개수
LC-City                       10.17%          10170
LC-Province                   11.18%          11180
LC-Country                    35.25%          35247
BO-Politics                    2.95%           2949
BO-Media                       3.23%           3226
BO-Military                    0.37%            372
PS-Name                       15.50%          15495
PS-Group                       3.57%           3574
BO-Economy                     4.68%           4682
BO-Education                   0.95%            947
LC-Space                       3.68%           3679
BO-Religion                    1.42%           1423
WA-Video                       1.47%           1470
PD-Food                        0.81%            813
WA-Performance                 0.02%             19
BO-Others                      1.02%           1020
PS-Character                   0.67%            672
LC-Building                    0.14%            140
WA-Music                       0.51%            506
LC-Others                      0.19%            193
BO-Law                         0.47%            474
PD-Sports                      0.08%             82
EV-Festival                    0.74%            738
EV-Incident                    0.03%             31
WA-Document                    0.15%            149
BO-Hotel                       0.01%              7
EV-Sports                      0.05%             52
BO-Food                        0.03%             29
PD-Clothing                    0.46%            463
BO-Sports                      0.04%             42
PD-Others                      0.02%             20
WA-Musical-Instrumnets         0.04%             40
PD-Vehicle                     0.01%              6
WA-ARC                         0.04%             42
PD-Drink                       0.01%              6
EV-Others                      0.02%             15
EV-Activity                    0.01%              6
99.99000000000004

In [11]:
pub_subj_df.sort_values(by = 'Pub_Subj 개수', ascending=False)

                    Pub_Subj 비율  Pub_Subj 개수
Kerajaan Kalinyamat      16.89%         1353
Kopi Joss                16.26%         1303
Pulau Samalona           10.26%          822
Kebudayaan Buni          10.17%          815
Kawa Daun                 8.76%          702
Siwalima Museum           4.62%          370
Baju bodo                 4.01%          321
Pura Lingsar              3.96%          317
Bambang                   3.89%          312
Pertamina                 2.42%          194
Solok                     2.33%          187
Anggi Lakes               1.86%          149
Air Terjun Oehala         1.82%          146
Batik                     1.62%          130
Sriwijaya                 1.50%          120
Mount Trikora             1.22%           98
Charles Tambu             1.19%           95
Ternate                   1.19%           95
Ikat                      1.12%           90
GARUDA                    1.06%           85
Sabang                    1.01%           81
Bima                      0.96%           77
Anggun                    0.75%           60
Jabodetabek               0.64%           51
Paniai Lakes              0.20%           16
Kesultanan Deli           0.14%           11
Pura Sakenan              0.11%            9
Pantai Lovina             0.04%            3
Kerajaan Kahuripan        0.01%            1

In [12]:
pub_date_df.sort_values(by = 'Pub_Date 개수', ascending=False)

     Pub_Date 비율  Pub_Date 개수
2017      22.56%         1808
2022      15.30%         1226
2021      11.56%          926
2020      11.38%          912
2023       8.00%          641
2016       7.08%          567
2018       5.87%          470
2015       5.62%          450
2019       5.57%          446
2014       5.17%          414
2013       1.91%          153

In [13]:
word_count_df.sort_values(by = 'Word_Count 개수', ascending=False)

    Word_Count 비율  Word_Count 개수
12          5.24%          13096
13          5.24%          13077
14          5.19%          12948
11          5.09%          12712
15          4.95%          12349
..            ...            ...
224         0.00%              1
207         0.00%              1
229         0.00%              1
179         0.00%              1
154         0.00%              1

[216 rows x 2 columns]

In [14]:
entities_df.sort_values(by = 'Entity 개수', ascending=False)

                      Entity 비율  Entity 개수
Indonesia                 8.36%       8362
Malaysia                  2.42%       2421
Iran                      1.76%       1764
Jakarta                   1.58%       1575
,                         1.55%       1550
...                         ...        ...
So Dam mengunggah         0.00%          1
Naeun Apink               0.00%          1
Beenzino                  0.00%          1
Na dalam mendukung        0.00%          1
kawasan Bukit Barisan     0.00%          1

[8935 rows x 2 columns]

In [15]:
entity_classes_df.sort_values(by = 'Entity 클래스 개수', ascending=False)

                       Entity 클래스 비율  Entity 클래스 개수
LC-Country                    35.25%          35247
PS-Name                       15.50%          15495
LC-Province                   11.18%          11180
LC-City                       10.17%          10170
BO-Economy                     4.68%           4682
LC-Space                       3.68%           3679
PS-Group                       3.57%           3574
BO-Media                       3.23%           3226
BO-Politics                    2.95%           2949
WA-Video                       1.47%           1470
BO-Religion                    1.42%           1423
BO-Others                      1.02%           1020
BO-Education                   0.95%            947
PD-Food                        0.81%            813
EV-Festival                    0.74%            738
PS-Character                   0.67%            672
WA-Music                       0.51%            506
BO-Law                         0.47%            474
PD-Clothing                    0.46%            463
BO-Military                    0.37%            372
LC-Others                      0.19%            193
WA-Document                    0.15%            149
LC-Building                    0.14%            140
PD-Sports                      0.08%             82
EV-Sports                      0.05%             52
BO-Sports                      0.04%             42
WA-ARC                         0.04%             42
WA-Musical-Instrumnets         0.04%             40
EV-Incident                    0.03%             31
BO-Food                        0.03%             29
PD-Others                      0.02%             20
WA-Performance                 0.02%             19
EV-Others                      0.02%             15
BO-Hotel                       0.01%              7
PD-Vehicle                     0.01%              6
PD-Drink                       0.01%              6
EV-Activity                    0.01%              6

<br>
<br>

### 압축해제한 폴더가 한 폴더 안에 있을 경우

In [17]:
import os
import json
import pandas as pd
from collections import defaultdict

total_word_count = 0
total_entities = 0

def process_json_files(file_path, pub_subj_count, pub_date_count, entities_count,
                        word_count_distribution, entity_classes_count):

    if file_path.endswith('.json') and not file_path.endswith('statistic.json'):
        with open(file_path, 'r', encoding='utf-8-sig') as file:
            data = json.load(file)
            pub_subj = data['Pub_Subj']
            pub_date = data['Pub_date']
            sentences = data['data']

            # 결과에 값을 추가
            pub_subj_count[pub_subj] += 1
            # pub_date_count[pub_date] += 1
            pub_date_count[pub_date.split('-')[0]] += 1

            for sentence in sentences:
                entities = sentence['Entities']
                word_count = int(sentence['Word_Count'])
                word_count_distribution[word_count] += 1
                global total_word_count
                # global total_entities
                total_word_count += 1
                # total_entities += 1
                for entity in entities:
                    entity_value = entity['entity']
                    entity_class = entity['entityClass']
                    entities_count[entity_value] += 1
                    entity_classes_count[entity_class] += 1

                    #global total_word_count
                    global total_entities
                    #total_word_count += 1
                    total_entities += 1

def calculate_percentage(count_dict, total):
    return {key: f'{value / total * 100:.2f}%' for key, value in count_dict.items()}

In [18]:
from tqdm import tqdm

# 폴더 경로 설정
base_folder = './가공완료_몇개만/'

# 결과를 저장할 딕셔너리 초기화
pub_subj_count = defaultdict(int)
pub_date_count = defaultdict(int)
entities_count = defaultdict(int)
word_count_distribution = defaultdict(int)
entity_classes_count = defaultdict(int)
total_entities = 0
total_files = 0
total_word_count = 0

# 폴더 순회 및 JSON 파일 처리
for root, dirs, files in os.walk(base_folder):
    for filename in tqdm(files):
        if filename.endswith('.json'):
            total_files += 1
            file_path = os.path.join(root, filename)
            process_json_files(file_path, pub_subj_count, pub_date_count, entities_count,
                                word_count_distribution, entity_classes_count)

# 비율 계산
pub_subj_percentages = calculate_percentage(pub_subj_count, total_files)
pub_date_percentages = calculate_percentage(pub_date_count, total_files)
entities_percentages = calculate_percentage(entities_count, total_entities)
word_count_percentages = calculate_percentage(word_count_distribution, total_word_count)
entity_classes_percentages = calculate_percentage(entity_classes_count, total_entities)

# 데이터프레임 생성
pub_subj_df = pd.DataFrame({'Pub_Subj 비율': pub_subj_percentages, 'Pub_Subj 개수': pub_subj_count})
pub_date_df = pd.DataFrame({'Pub_Date 비율': pub_date_percentages, 'Pub_Date 개수': pub_date_count})
entities_df = pd.DataFrame({'Entity 비율': entities_percentages, 'Entity 개수': entities_count})
word_count_df = pd.DataFrame({'Word_Count 비율': word_count_percentages, 'Word_Count 개수': word_count_distribution})
entity_classes_df = pd.DataFrame({'Entity 클래스 비율': entity_classes_percentages, 'Entity 클래스 개수': entity_classes_count})

# 결과 출력
print('Pub_Subj 데이터프레임:')
print(pub_subj_df)
print(sum(pub_subj_df['Pub_Subj 비율'].str.rstrip('%').astype(float)))

print('\nPub_Date 데이터프레임:')
print(pub_date_df)
print(sum(pub_date_df['Pub_Date 비율'].str.rstrip('%').astype(float)))

print('\nEntities 데이터프레임:')
print(entities_df)
print(sum(entities_df['Entity 비율'].str.rstrip('%').astype(float)))

print('\nWord_Count 데이터프레임:')
print(word_count_df)
print(sum(word_count_df['Word_Count 비율'].str.rstrip('%').astype(float)))

print('\nEntity 클래스 데이터프레임:')
print(entity_classes_df)
print(sum(entity_classes_df['Entity 클래스 비율'].str.rstrip('%').astype(float)))

0it [00:00, ?it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]
100%|██████████| 12630/12630 [00:04<00:00, 2674.63it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]
100%|██████████| 8013/8013 [00:02<00:00, 2920.19it/s]
0it [00:00, ?it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]
 25%|██▍       | 24621/100000 [01:57<05:59, 209.64it/s]

KeyboardInterrupt:

In [28]:
pub_subj_df.sort_values(by = 'Pub_Subj 개수', ascending=False)

                        Pub_Subj 비율  Pub_Subj 개수
Pantai Koka                  19.97%         4123
Pulau Samalona               17.01%         3512
Serimpi Dance                 9.45%         1950
We Island                     7.15%         1477
Kerajaan Kalinyamat           6.55%         1353
Kopi Joss                     6.31%         1303
kalong Island                 4.39%          907
Kebudayaan Buni               3.95%          815
Kawa Daun                     3.40%          702
Rammang-Rammang Village       2.80%          578
Pontianak                     2.49%          514
Siwalima Museum               1.79%          370
Balikpapan                    1.71%          352
Baju bodo                     1.55%          321
Pura Lingsar                  1.54%          317
Bambang                       1.51%          312
Pertamina                     0.94%          194
Solok                         0.91%          187
Anggi Lakes                   0.72%          149
Air Terjun Oehala             0.71%          146
Batik                         0.63%          130
Sriwijaya                     0.58%          120
Mount Trikora                 0.47%           98
Ternate                       0.46%           95
Charles Tambu                 0.46%           95
Ikat                          0.44%           90
GARUDA                        0.41%           85
Sabang                        0.39%           81
Bima                          0.37%           77
Anggun                        0.29%           60
Jabodetabek                   0.25%           51
Lengkuas Island               0.12%           24
Paniai Lakes                  0.08%           16
Kesultanan Deli               0.05%           11
Pura Sakenan                  0.04%            9
Maratua Island                0.04%            9
Kakaban Island                0.03%            6
Pantai Lovina                 0.01%            3
Kerajaan Kahuripan            0.00%            1

In [29]:
pub_date_df.sort_values(by = 'Pub_Date 개수', ascending=False)

           Pub_Date 비율  Pub_Date 개수
2017-07-22       0.30%           61
2017-07-19       0.29%           60
2017-06-20       0.29%           60
2017-07-17       0.28%           57
2017-07-18       0.27%           56
...                ...          ...
2015-07-11       0.00%            1
2015-07-28       0.00%            1
2015-12-18       0.00%            1
2016-06-11       0.00%            1
2014-01-30       0.00%            1

[3512 rows x 2 columns]

In [30]:
entities_df.sort_values(by = 'Entity 개수', ascending=False)

                    Entity 비율  Entity 개수
Indonesia               3.97%      27736
Bali                    0.84%       5889
,                       0.73%       5108
Jakarta                 0.69%       4834
Malaysia                0.63%       4384
...                       ...        ...
Dmost Entertainment     0.00%          1
Chanhee                 0.00%          1
Lim                     0.00%          1
Daniel dan              0.00%          1
Selatan Nova            0.00%          1

[18448 rows x 2 columns]

In [31]:
word_count_df.sort_values(by = 'Word_Count 개수', ascending=False)

    Word_Count 비율  Word_Count 개수
12          5.22%          36435
13          5.20%          36324
14          5.17%          36103
15          5.06%          35297
11          4.99%          34864
..            ...            ...
492         0.00%              1
388         0.00%              1
311         0.00%              1
229         0.00%              1
167         0.00%              1

[246 rows x 2 columns]

In [35]:
entity_classes_df.sort_values(by = 'Entity 클래스 개수', ascending= False)

                       Entity 클래스 비율  Entity 클래스 개수
LC-Country                    13.72%          95796
PS-Name                        5.76%          40184
LC-Province                    5.70%          39826
LC-City                        4.30%          30037
LC-Space                       2.31%          16099
PS-Group                       1.79%          12471
BO-Politics                    1.64%          11427
BO-Media                       1.48%          10299
BO-Economy                     1.44%          10062
WA-Video                       0.44%           3069
BO-Others                      0.36%           2547
BO-Education                   0.36%           2503
BO-Religion                    0.35%           2410
WA-Music                       0.30%           2074
EV-Festival                    0.21%           1465
PD-Food                        0.19%           1360
BO-Military                    0.17%           1168
BO-Law                         0.16%           1114
PS-Character                   0.15%           1052
PD-Clothing                    0.12%            807
LC-Building                    0.07%            470
LC-Others                      0.05%            379
WA-Document                    0.04%            297
PD-Sports                      0.03%            211
WA-Musical-Instrumnets         0.02%            152
EV-Sports                      0.02%            137
WA-Performance                 0.02%            106
WA-ARC                         0.01%             90
BO-Sports                      0.01%             87
EV-Incident                    0.01%             86
PD-Others                      0.01%             78
BO-Food                        0.01%             40
EV-Others                      0.00%             25
EV-Activity                    0.00%             18
PD-Drink                       0.00%             15
PD-Vehicle                     0.00%             14
PD-Cosmetics                   0.00%             14
BO-Hotel                       0.00%             11